app:
    regcred: regcred

    image:
        repository: ghcr.io/mohannadwahmad17/MohannadPortfolio

    port: 3000
    health: /

    ingress:
        enabled: true
        url: portfolio.mohannad.cloud.lublabs.com
  